plugins { id 'com.android.library' }
android { namespace 'dev.ghostcode.wearinstaller.common'; compileSdk 35
 defaultConfig { minSdk 30 }
 compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
dependencies { api 'com.google.android.gms:play-services-wearable:20.0.1'; testImplementation 'junit:junit:4.13.2' }
